### ISSUE TITLE
Tag v0.5.0 has .ipkg version 0.3.0

### ISSUE THREAD

**Issue by joelberkeley** [stefan-hoeck/idris2-pretty-show#4]
I'd expect it to have version 0.5.0. Have I misunderstood?

**Comment by kayhide** [comment]
Hi, I had hit by this problem as well.

Currently, `v0.5.0` is tagged on this commit:
https://github.com/stefan-hoeck/idris2-pretty-show/commit/52ea3e1c2723add900ed4ed5725260dcc3381da6

Actually, the package version is updated on this commit which is just one after the commit above:
https://github.com/stefan-hoeck/idris2-pretty-show/commit/4f6beeca0f1899bc8fcf2fe979ea293c00e466f8

**Comment by stefan-hoeck** [comment]
Yes, I see the issue now. I think I just add a new `v0.5.1` tag with the correct version in the .ipkg file.

**Comment by kayhide** [comment]
That sounds reasonable.
Could you do that?

**Comment by stefan-hoeck** [comment]
Thanks. Then I'm closing this.

**Comment by kayhide** [comment]
It's working for me, too.
Thanks.
